language: java
jdk:
  - openjdk7
before_install:
  - sudo add-apt-repository ppa:chris-lea/protobuf -y
  - sudo apt-get update
  - sudo apt-get install protobuf-compiler=2.5.0-1chl1~precise1 -y
  - sudo apt-get install libprotoc7=2.5.0-1chl1~precise1 -y
  - sudo apt-get install libprotobuf7=2.5.0-1chl1~precise1 -y
  - ./src/main/sh/generate_toolchains.sh
  - mvn --toolchains toolchains.xml --file plugin/pom.xml install 
install: mvn --toolchains toolchains.xml install -DskipTests=true
script: mvn --toolchains toolchains.xml test
